from functools import lru_cache
from typing import Any

import boto3
from botocore.exceptions import BotoCoreError, ClientError
from transformers import pipeline


class GenerationError(RuntimeError):
    """Raised when an answer cannot be generated by Amazon Bedrock."""


@lru_cache(maxsize=1)
def get_local_generator(model_id: str):
    """Load and cache a small CPU-compatible text generation model."""
    return pipeline(
        task="text2text-generation",
        model=model_id,
        device=-1,
    )


def build_evidence(results: list[dict[str, Any]]) -> str:
    """Format retrieved chunks as numbered evidence for the chat model."""
    sections = []

    for position, result in enumerate(results, start=1):
        source = result.get("source_file", "unknown.pdf")
        page = result.get("page_number", "unknown")
        text = result.get("text", "").strip()
        sections.append(
            f"[Evidence {position} | Source: {source} | Page: {page}]\n{text}"
        )

    return "\n\n".join(sections)


def generate_grounded_answer(
    question: str,
    results: list[dict[str, Any]],
    model_id: str,
    region: str,
) -> str:
    """Generate an evidence-grounded answer with Amazon Bedrock Converse."""
    if not model_id.strip():
        raise ValueError("CHAT_MODEL_ID is not configured.")

    if not results:
        return "I could not find relevant evidence in the selected report."

    evidence = build_evidence(results)
    prompt = f"""Question: {question}

Evidence from the selected annual report:
{evidence}

Answer the question using only the evidence above. Cite every factual claim using
the page number in the form [Page X]. If the evidence is insufficient, clearly
say that the answer is not available in the selected report. Do not invent
figures, dates, business segments, or conclusions. Keep the answer concise and
financially precise."""

    client = boto3.client("bedrock-runtime", region_name=region)

    try:
        response = client.converse(
            modelId=model_id.strip(),
            system=[
                {
                    "text": (
                        "You are a financial-report research assistant. "
                        "Use only supplied evidence and preserve numerical accuracy."
                    )
                }
            ],
            messages=[
                {
                    "role": "user",
                    "content": [{"text": prompt}],
                }
            ],
            inferenceConfig={
                "maxTokens": 900,
                "temperature": 0.1,
                "topP": 0.9,
            },
        )
    except (BotoCoreError, ClientError) as error:
        raise GenerationError(
            f"Amazon Bedrock could not generate an answer: {error}"
        ) from error

    content = response.get("output", {}).get("message", {}).get("content", [])
    answer_parts = [item["text"] for item in content if item.get("text")]

    if not answer_parts:
        raise GenerationError("Amazon Bedrock returned an empty answer.")

    return "\n".join(answer_parts)


def generate_local_answer(
    question: str,
    results: list[dict[str, Any]],
    model_id: str,
) -> str:
    """Generate a grounded answer locally when Bedrock is unavailable."""
    if not results:
        return "I could not find relevant evidence in the selected report."

    compact_evidence = []
    pages = []

    for result in results[:3]:
        page = result.get("page_number", "unknown")
        pages.append(page)
        text = result.get("text", "").strip()[:550]
        compact_evidence.append(f"Page {page}: {text}")

    prompt = (
        "Answer the financial question using only the report evidence. "
        "If the evidence is insufficient, say so. Do not invent numbers.\n\n"
        f"Question: {question}\n\n"
        f"Evidence:\n{' '.join(compact_evidence)}\n\n"
        "Concise answer:"
    )

    try:
        generator = get_local_generator(model_id)
        output = generator(
            prompt,
            max_new_tokens=220,
            do_sample=False,
        )
    except (OSError, RuntimeError, ValueError) as error:
        raise GenerationError(
            f"The local answer model could not run: {error}"
        ) from error

    answer = output[0].get("generated_text", "").strip() if output else ""

    if not answer:
        raise GenerationError("The local answer model returned an empty answer.")

    citations = ", ".join(f"[Page {page}]" for page in dict.fromkeys(pages))
    return f"{answer}\n\n**Retrieved sources:** {citations}"
